version: '3.9'

services:
  nginx:
    # container_name: shivam-nginx
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

  # api is the name of the backend, you can name it anything
  api:
    build: . # Path to Dockerfile
    restart: unless-stopped
    ports:
      - 5000:5000 # Left is local and right is docker (I Believe)
      - 9229:9229 # Debugger port
    # Volumes is used so that we do not build the entire image upon a single file change
    volumes:
      - .:/app # Left is local and after : is directory set in Dockerfile
      - /app/node_modules # Specifies to use Docker node_modules within Docker only and share everything else with us outside
    command: yarn build:start # This will override the CMD command which is present in Dockerfile
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=5000
